### PR TITLE
Containerized snapshot restore

### PR DESCRIPTION
**Pull request by MattSurabian**
Avoid random Python issues when running in different platforms by doing snapshots in an ad-hoc container.

### CODE REVIEW

**Comment by MattSurabian** [comment]
Could use testing from different environments
  - `make init`
  - `make snapshot`
  - `make destroy`
  - `make restore`

**Comment by tkellen** [comment]
```
❯ git checkout containerized-snapshot-restore
Branch 'containerized-snapshot-restore' set up to track remote branch 'containerized-snapshot-restore' from 'origin'.
Switched to a new branch 'containerized-snapshot-restore'

~/vault-playground containerized-snapshot-restore
❯ make init

Spin up local DynamoDB:
9eb4b38f0d19e604bc49795d3a08388c4a64733060f4fc6098fa5bc443c0ee95

Spin up Vault server #1
992bbf36af98aa57182a7a8d2935ee763007beabb5022292a710ba0b8a670f08

Spin up Vault server #2
17d8927accad194115fa1da5faa80108d8374087b4d11561962e741cb9e7d017

Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 1
Unseal Nonce: 40c2d629-d4ca-9207-690b-842984a33725
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 2
Unseal Nonce: 40c2d629-d4ca-9207-690b-842984a33725
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Unseal Nonce:
Vault is already unsealed.
Vault is already unsealed.
Vault Initialization information dumped to: /Users/tkellen/.vault-playground/init_dumps/992bbf36af98.json
Root Token:
f5aa7707-73aa-be92-a282-4bd21ab950ba

Vault Playground Test Environment Deployed...

Vault Status:
Vault #1
Seal Type: shamir
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Unseal Nonce:
Version: 0.9.1
Cluster Name: vault-cluster-df9d2314
Cluster ID: b20bbadf-14dc-6dac-93ef-c1c41eb60d21

High-Availability Enabled: true
	Mode: active
	Leader Cluster Address: https://vp-vault1:8201

Vault #2
Error response from daemon: Container 17d8927accad194115fa1da5faa80108d8374087b4d11561962e741cb9e7d017 is not running


Vault is now running at:
vp-vault1: http://0.0.0.0:32769

There are two ways to communicate with Vault
Use Docker exec:
   docker exec vp-vault1 vault status
or set your host's VAULT_ADDR environment variable to communicate directly using the Vault CLI.
   export VAULT_ADDR=$(make vault-leader)
Note that if Vault is still sealed there will be no leader and make vault-leader will error

~/vault-playground containerized-snapshot-restore 14s
❯ make snapshot
Snapshotting the vault-playground table on the local DynamoDB instance...
Unable to find image 'mattsurabian/dynamodump:1.1.1' locally
1.1.1: Pulling from mattsurabian/dynamodump
2fdfe1cd78c2: Pull complete
7511e2b5361e: Pull complete
5eb0973099d1: Pull complete
862756b6cec2: Pull complete
c79044b267f7: Pull complete
93334269209d: Pull complete
6a73452c000a: Pull complete
Digest: sha256:50d7c62aed5a04f63efd2ae0f4c739d85194a0356e01ed816d0703efdac86cba
Status: Downloaded newer image for mattsurabian/dynamodump:1.1.1
INFO:root:Found 1 table(s) in DynamoDB host to backup: vault-playground
INFO:root:Starting backup for vault-playground..
INFO:root:Dumping table schema for vault-playground
INFO:root:Dumping table items for vault-playground
INFO:root:Backup for vault-playground table completed. Time taken: 0:00:25
INFO:root:Backup of table(s) vault-playground completed!
Wrote snapshot to /Users/tkellen/.vault-playground/snapshots/992bbf36af98-2018-01-10-14-19-58

~/vault-playground containerized-snapshot-restore 46s
❯ make destroy
17d8927accad194115fa1da5faa80108d8374087b4d11561962e741cb9e7d017
992bbf36af98aa57182a7a8d2935ee763007beabb5022292a710ba0b8a670f08
9eb4b38f0d19e604bc49795d3a08388c4a64733060f4fc6098fa5bc443c0ee95
vp
To purge all cached data run the purge script

~/vault-playground containerized-snapshot-restore
❯ make restore
1) /Users/tkellen/.vault-playground/snapshots/992bbf36af98-2018-01-10-14-19-58
2) Cancel
Please select a snapshot to restore: 1
Restoring /Users/tkellen/.vault-playground/snapshots/992bbf36af98-2018-01-10-14-19-58...
Restoring the vault-playground table on a local DynamoDB instance...

Spin up local DynamoDB:
bf9e4feb89c7e343e5151833caeaa72425d81c7c7e31aeafe18d56202cb428af

Spin up Vault server #1
2f2922561c92e10e903ba1d5d279daea63b80ea77fdbcc62fbf41f508c594e76

Spin up Vault server #2
a61e30bbb335520e1dafef4cbbd57a7bc9a9dd8f36c757854432d64f427204a6


Vault Playground Test Environment Deployed...

Vault Status:
Auto initialization of Vault was disabled... no status to report.

Vault is now running at:
vp-vault2: http://0.0.0.0:32773
vp-vault1: http://0.0.0.0:32772

There are two ways to communicate with Vault
Use Docker exec:
   docker exec vp-vault1 vault status
or set your host's VAULT_ADDR environment variable to communicate directly using the Vault CLI.
   export VAULT_ADDR=$(make vault-leader)
Note that if Vault is still sealed there will be no leader and make vault-leader will error
```

**Comment by tkellen** [comment]
Whoops, posted that too soon. My restore seems to be hung. This is on OSX with Docker Community Edition 17.0.9.1-ce-mac42 (21090).

**Comment by tkellen** [comment]
This eventually timed out with the following:
```

^CTraceback (most recent call last):
  File "/usr/local/bin/dynamodump", line 1044, in <module>
    main()
  File "/usr/local/bin/dynamodump", line 1019, in main
    delete_table(conn, sleep_interval, dest_table)
  File "/usr/local/bin/dynamodump", line 349, in delete_table
    conn.delete_table(table_name)
  File "/usr/local/lib/python2.7/site-packages/boto/dynamodb2/layer1.py", line 956, in delete_table
    body=json.dumps(params))
  File "/usr/local/lib/python2.7/site-packages/boto/dynamodb2/layer1.py", line 2842, in make_request
    retry_handler=self._retry_handler)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
socket.error: [Errno 99] Address not available
Error checking seal status: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/seal-status
Code: 400. Errors:

* server is not yet initialized
Error checking seal status: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/seal-status
Code: 400. Errors:

* server is not yet initialized
Error checking seal status: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/seal-status
Code: 400. Errors:

* server is not yet initialized
Error checking seal status: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/seal-status
Code: 400. Errors:

* server is not yet initialized
Error checking seal status: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/seal-status
Code: 400. Errors:

* server is not yet initialized
Error checking seal status: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/seal-status
Code: 400. Errors:

* server is not yet initialized
Error checking seal status: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/seal-status
Code: 400. Errors:

* server is not yet initialized
Error checking seal status: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/seal-status
Code: 400. Errors:

* server is not yet initialized
Error checking seal status: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/seal-status
Code: 400. Errors:

* server is not yet initialized
Error checking seal status: Error making API request.

URL: GET http://127.0.0.1:8200/v1/sys/seal-status
Code: 400. Errors:

* server is not yet initialized

Vault Initialization information dumped to: /Users/tkellen/.vault-playground/init_dumps/2f2922561c92.json
Root Token:
f5aa7707-73aa-be92-a282-4bd21ab950ba
```

**Comment by MattSurabian** [comment]
@tkellen hopefully that issue should be fixed now.

**Comment by tkellen** [comment]
It surely is. A thing of beauty my friend.
```
~/vault-playground containerized-snapshot-restore
❯ make init

Spin up local DynamoDB:
e1d98b18c7563f1df883ec614487ecb5a9bc6a5f10dd4b972369566d25880588

Spin up Vault server #1
142171bf67744243b5ccd9e79a34cff3efc7413ac5bc4afabfb4f7f50b14ee1f

Spin up Vault server #2
ebc6affd5f786ff993ad566c8e8333d81a401859738e04e9cfbecbe915297264

Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 1
Unseal Nonce: 47f2fce1-bf7d-1df8-d125-b76b295bbf31
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 2
Unseal Nonce: 47f2fce1-bf7d-1df8-d125-b76b295bbf31
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Unseal Nonce:
Vault is already unsealed.
Vault is already unsealed.
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 1
Unseal Nonce: 23c82e92-1f96-e2c6-0052-3a51181023cd
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 2
Unseal Nonce: 23c82e92-1f96-e2c6-0052-3a51181023cd
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Unseal Nonce:
Vault is already unsealed.
Vault is already unsealed.
Vault Initialization information dumped to: /Users/tkellen/.vault-playground/init_dumps/142171bf6774.json
Root Token:
6441ada9-10b2-62c7-a858-f9d0059663b4

Vault Playground Test Environment Deployed...

Vault Status:
Vault #1
Seal Type: shamir
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Unseal Nonce:
Version: 0.9.1
Cluster Name: vault-cluster-675c86a7
Cluster ID: 98a32696-ac55-fe40-6ac0-a6df112797bf

High-Availability Enabled: true
	Mode: standby
	Leader Cluster Address: https://vp-vault2:8201

Vault #2
Seal Type: shamir
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Unseal Nonce:
Version: 0.9.1
Cluster Name: vault-cluster-675c86a7
Cluster ID: 98a32696-ac55-fe40-6ac0-a6df112797bf

High-Availability Enabled: true
	Mode: active
	Leader Cluster Address: https://vp-vault2:8201


Vault is now running at:
vp-vault2: http://0.0.0.0:32779
vp-vault1: http://0.0.0.0:32778

There are two ways to communicate with Vault
Use Docker exec:
   docker exec vp-vault1 vault status
or set your host's VAULT_ADDR environment variable to communicate directly using the Vault CLI.
   export VAULT_ADDR=$(make vault-leader)
Note that if Vault is still sealed there will be no leader and make vault-leader will error

~/vault-playground containerized-snapshot-restore 15s
❯ docker exec vp-vault1 vault status
Seal Type: shamir
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Unseal Nonce:
Version: 0.9.1
Cluster Name: vault-cluster-675c86a7
Cluster ID: 98a32696-ac55-fe40-6ac0-a6df112797bf

High-Availability Enabled: true
	Mode: standby
	Leader Cluster Address: https://vp-vault2:8201

~/vault-playground containerized-snapshot-restore
❯ make snapshot
Snapshotting the vault-playground table on the local DynamoDB instance...
INFO:root:Found 1 table(s) in DynamoDB host to backup: vault-playground
INFO:root:Starting backup for vault-playground..
INFO:root:Dumping table schema for vault-playground
INFO:root:Dumping table items for vault-playground
INFO:root:Backup for vault-playground table completed. Time taken: 0:00:25
INFO:root:Backup of table(s) vault-playground completed!
Wrote snapshot to /Users/tkellen/.vault-playground/snapshots/142171bf6774-2018-01-10-21-15-19

~/vault-playground containerized-snapshot-restore 27s
❯ make destroy
ebc6affd5f786ff993ad566c8e8333d81a401859738e04e9cfbecbe915297264
142171bf67744243b5ccd9e79a34cff3efc7413ac5bc4afabfb4f7f50b14ee1f
e1d98b18c7563f1df883ec614487ecb5a9bc6a5f10dd4b972369566d25880588
vp
To purge all cached data run the purge script

~/vault-playground containerized-snapshot-restore
❯ make restore
1) /Users/tkellen/.vault-playground/snapshots/142171bf6774-2018-01-10-21-15-19
2) /Users/tkellen/.vault-playground/snapshots/992bbf36af98-2018-01-10-14-19-58
3) Cancel
Please select a snapshot to restore: 1
Restoring /Users/tkellen/.vault-playground/snapshots/142171bf6774-2018-01-10-21-15-19...
Restoring the vault-playground table on a local DynamoDB instance...

Spin up local DynamoDB:
abf89d1dfb674d25ba94ce6d69de980b3aa124bd99834985c90938b69e174200

Spin up Vault server #1
50c7dc58b5a4b2967bf41b4cbd4781a4025312b6c0493a3597c94d00e16f66c6

Spin up Vault server #2
65313f36fd4a39e4c597db574af573d60fdf55619289a164d14ebdd08f027306


Vault Playground Test Environment Deployed...

Vault Status:
Auto initialization of Vault was disabled... no status to report.

Vault is now running at:
vp-vault2: http://0.0.0.0:32782
vp-vault1: http://0.0.0.0:32781

There are two ways to communicate with Vault
Use Docker exec:
   docker exec vp-vault1 vault status
or set your host's VAULT_ADDR environment variable to communicate directly using the Vault CLI.
   export VAULT_ADDR=$(make vault-leader)
Note that if Vault is still sealed there will be no leader and make vault-leader will error
INFO:root:vault-playground table deleted!
INFO:root:Starting restore for vault-playground to vault-playground..
INFO:root:Creating vault-playground table with temp write capacity of 25
INFO:root:vault-playground created.
INFO:root:Restoring data for vault-playground table..
INFO:root:Processing 0001.json of vault-playground
INFO:root:Updating vault-playground table read capacity to: 5, write capacity to: 5
INFO:root:vault-playground active.
INFO:root:Restore for vault-playground to vault-playground table completed. Time taken: 0:00:00
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 1
Unseal Nonce: 6cd2cfbe-4485-aa27-ef12-fd0ee0c39e1f
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 2
Unseal Nonce: 6cd2cfbe-4485-aa27-ef12-fd0ee0c39e1f
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Unseal Nonce:
Vault is already unsealed.
Vault is already unsealed.
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 1
Unseal Nonce: 8e848372-b54f-181e-d79e-9a331cca4049
Sealed: true
Key Shares: 5
Key Threshold: 3
Unseal Progress: 2
Unseal Nonce: 8e848372-b54f-181e-d79e-9a331cca4049
Sealed: false
Key Shares: 5
Key Threshold: 3
Unseal Progress: 0
Unseal Nonce:
Vault is already unsealed.
Vault is already unsealed.

Vault Initialization information dumped to: /Users/tkellen/.vault-playground/init_dumps/50c7dc58b5a4.json
Root Token:
6441ada9-10b2-62c7-a858-f9d0059663b4
```

**Comment by adamjarret** [comment]
**macOS Sierra 10.12.6**
**Docker version 17.12.0-ce, build c97c6d6**

No errors here.

    ❯ git clone https://github.com/Zipcar/vault-playground.git
    Cloning into 'vault-playground'...
    remote: Counting objects: 203, done.
    remote: Compressing objects: 100% (120/120), done.
    remote: Total 203 (delta 128), reused 151 (delta 81), pack-reused 0
    Receiving objects: 100% (203/203), 50.67 KiB | 154.00 KiB/s, done.
    Resolving deltas: 100% (128/128), done.
    ❯ cd vault-playground/
    ❯ git checkout containerized-snapshot-restore
    Branch 'containerized-snapshot-restore' set up to track remote branch 'containerized-snapshot-restore' from 'origin'.
    Switched to a new branch 'containerized-snapshot-restore'

    ❯ make init

    Spin up local DynamoDB:
    Unable to find image 'dwmkerr/dynamodb:latest' locally
    latest: Pulling from dwmkerr/dynamodb
    d08a2c3112d4: Pull complete 
    25de13746f41: Pull complete 
    34a279a4928d: Pull complete 
    13bece0db804: Pull complete 
    d6654241ffed: Pull complete 
    0cd96fd023ff: Pull complete 
    2c3e90b51ce4: Pull complete 
    f17a3b562abe: Pull complete 
    Digest: sha256:e6fdef4e99ba08edaacbc19e19435589035f4ee6870783d5e1e60e72fa5416e4
    Status: Downloaded newer image for dwmkerr/dynamodb:latest
    3a8af7e6bd7fa466b8ec30bd1f76eeb65fccd8afaeb283601281a2de84204b59

    Spin up Vault server #1
    Unable to find image 'vault:latest' locally
    latest: Pulling from library/vault
    605ce1bd3f31: Pull complete 
    ae1aea0a72c4: Pull complete 
    156b82fd2ee4: Pull complete 
    5073e473de95: Pull complete 
    77918083a8cf: Pull complete 
    Digest: sha256:69d1ee4f7f77272cf5c63f66f93a7374109ab0d6271abce7ca3d99ad57b076b5
    Status: Downloaded newer image for vault:latest
    70b2dd7368f4dab67d22a03bb05c792251394ad673c6734e4fe7ab07727385ec

    Spin up Vault server #2
    20ac87819e002616411e4f959215823ce111cb1a0344f5d200849301c4aa09d3

    Sealed: true
    Key Shares: 5
    Key Threshold: 3
    Unseal Progress: 1
    Unseal Nonce: 78a01433-1ef4-3672-0e33-a5df6f83b502
    Sealed: true
    Key Shares: 5
    Key Threshold: 3
    Unseal Progress: 2
    Unseal Nonce: 78a01433-1ef4-3672-0e33-a5df6f83b502
    Sealed: false
    Key Shares: 5
    Key Threshold: 3
    Unseal Progress: 0
    Unseal Nonce: 
    Vault is already unsealed.
    Vault is already unsealed.
    Sealed: true
    Key Shares: 5
    Key Threshold: 3
    Unseal Progress: 1
    Unseal Nonce: c9451888-66fd-061f-d42c-1b637c774826
    Sealed: true
    Key Shares: 5
    Key Threshold: 3
    Unseal Progress: 2
    Unseal Nonce: c9451888-66fd-061f-d42c-1b637c774826
    Sealed: false
    Key Shares: 5
    Key Threshold: 3
    Unseal Progress: 0
    Unseal Nonce: 
    Vault is already unsealed.
    Vault is already unsealed.
    Vault Initialization information dumped to: /Users/adam/.vault-playground/init_dumps/70b2dd7368f4.json
    Root Token:
    485fbcb2-e8c3-41db-e266-383b0d0622ef

    Vault Playground Test Environment Deployed...

    Vault Status:
    Vault #1
    Seal Type: shamir
    Sealed: false
    Key Shares: 5
    Key Threshold: 3
    Unseal Progress: 0
    Unseal Nonce: 
    Version: 0.9.1
    Cluster Name: vault-cluster-70f49a6f
    Cluster ID: 6708d347-ec76-52c3-0aee-966606030cc3

    High-Availability Enabled: true
        Mode: standby
        Leader Cluster Address: https://vp-vault2:8201

    Vault #2
    Seal Type: shamir
    Sealed: false
    Key Shares: 5
    Key Threshold: 3
    Unseal Progress: 0
    Unseal Nonce: 
    Version: 0.9.1
    Cluster Name: vault-cluster-70f49a6f
    Cluster ID: 6708d347-ec76-52c3-0aee-966606030cc3

    High-Availability Enabled: true
        Mode: active
        Leader Cluster Address: https://vp-vault2:8201


    Vault is now running at:
    vp-vault2: http://0.0.0.0:32770
    vp-vault1: http://0.0.0.0:32769

    There are two ways to communicate with Vault
    Use Docker exec: 
       docker exec vp-vault1 vault status
    or set your host's VAULT_ADDR environment variable to communicate directly using the Vault CLI.
       export VAULT_ADDR=$(make vault-leader)
    Note that if Vault is still sealed there will be no leader and make vault-leader will error
    ❯ make snapshot
    Snapshotting the vault-playground table on the local DynamoDB instance...
    Unable to find image 'mattsurabian/dynamodump:1.1.1' locally
    1.1.1: Pulling from mattsurabian/dynamodump
    2fdfe1cd78c2: Pull complete 
    7511e2b5361e: Pull complete 
    5eb0973099d1: Pull complete 
    862756b6cec2: Pull complete 
    c79044b267f7: Pull complete 
    93334269209d: Pull complete 
    6a73452c000a: Pull complete 
    Digest: sha256:50d7c62aed5a04f63efd2ae0f4c739d85194a0356e01ed816d0703efdac86cba
    Status: Downloaded newer image for mattsurabian/dynamodump:1.1.1
    INFO:root:Found 1 table(s) in DynamoDB host to backup: vault-playground
    INFO:root:Starting backup for vault-playground..
    INFO:root:Dumping table schema for vault-playground
    INFO:root:Dumping table items for vault-playground
    INFO:root:Backup for vault-playground table completed. Time taken: 0:00:25
    INFO:root:Backup of table(s) vault-playground completed!
    Wrote snapshot to /Users/adam/.vault-playground/snapshots/70b2dd7368f4-2018-01-10-15-59-16
    ❯ make destroy
    20ac87819e002616411e4f959215823ce111cb1a0344f5d200849301c4aa09d3
    70b2dd7368f4dab67d22a03bb05c792251394ad673c6734e4fe7ab07727385ec
    3a8af7e6bd7fa466b8ec30bd1f76eeb65fccd8afaeb283601281a2de84204b59
    vp
    To purge all cached data run the purge script
    ❯ make restore
    1) /Users/adam/.vault-playground/snapshots/70b2dd7368f4-2018-01-10-15-59-16
    2) Cancel
    Please select a snapshot to restore: 1
    Restoring /Users/adam/.vault-playground/snapshots/70b2dd7368f4-2018-01-10-15-59-16...
    Restoring the vault-playground table on a local DynamoDB instance...

    Spin up local DynamoDB:
    9b89866f487ab40b29960b7094d73183d4dfdf76e41526ce7a6a4f8aaf19fec0

    Spin up Vault server #1
    0f19032834a310ad371a6389fc361e07d42d4691d541f1560a39131e36bab6a4

    Spin up Vault server #2
    fedc61386a0ab59f97b02561413f76e7b81b1237d301dc17884e7c212e4000f6


    Vault Playground Test Environment Deployed...

    Vault Status:
    Auto initialization of Vault was disabled... no status to report.

    Vault is now running at:
    vp-vault2: http://0.0.0.0:32773
    vp-vault1: http://0.0.0.0:32772

    There are two ways to communicate with Vault
    Use Docker exec: 
       docker exec vp-vault1 vault status
    or set your host's VAULT_ADDR environment variable to communicate directly using the Vault CLI.
       export VAULT_ADDR=$(make vault-leader)
    Note that if Vault is still sealed there will be no leader and make vault-leader will error
    INFO:root:vault-playground table deleted!
    INFO:root:Starting restore for vault-playground to vault-playground..
    INFO:root:Creating vault-playground table with temp write capacity of 25
    INFO:root:vault-playground created.
    INFO:root:Restoring data for vault-playground table..
    INFO:root:Processing 0001.json of vault-playground
    INFO:root:Updating vault-playground table read capacity to: 5, write capacity to: 5
    INFO:root:vault-playground active.
    INFO:root:Restore for vault-playground to vault-playground table completed. Time taken: 0:00:01
    Sealed: true
    Key Shares: 5
    Key Threshold: 3
    Unseal Progress: 1
    Unseal Nonce: 8e91f192-3997-699d-957a-47ea98e77fb4
    Sealed: true
    Key Shares: 5
    Key Threshold: 3
    Unseal Progress: 2
    Unseal Nonce: 8e91f192-3997-699d-957a-47ea98e77fb4
    Sealed: false
    Key Shares: 5
    Key Threshold: 3
    Unseal Progress: 0
    Unseal Nonce: 
    Vault is already unsealed.
    Vault is already unsealed.
    Sealed: true
    Key Shares: 5
    Key Threshold: 3
    Unseal Progress: 1
    Unseal Nonce: bf1e2421-8d81-4f90-ce5e-bc911daa49e6
    Sealed: true
    Key Shares: 5
    Key Threshold: 3
    Unseal Progress: 2
    Unseal Nonce: bf1e2421-8d81-4f90-ce5e-bc911daa49e6
    Sealed: false
    Key Shares: 5
    Key Threshold: 3
    Unseal Progress: 0
    Unseal Nonce: 
    Vault is already unsealed.
    Vault is already unsealed.

    Vault Initialization information dumped to: /Users/adam/.vault-playground/init_dumps/0f19032834a3.json
    Root Token:
    485fbcb2-e8c3-41db-e266-383b0d0622ef

    ❯ make purge
    Vault Playground cache (/Users/adam/.vault-playground) purged

**Comment by MattSurabian** [comment]
Thanks yall!

**Pull request merged**
